### ISSUE TITLE
Support for other versions of Chrome

### ISSUE THREAD

**Issue by 1Ondr1** [alyssaxuu/omni#24]
Will there be support for browsers on chromium below the version? I'm using the Cent browser in which the version of chromium is 86. And I can't add Omni in any way. An error appears Invalid value for 'web_accessible_resources[0].

**Comment by alyssaxuu** [comment]
That must be because Omni uses manifest V3, which older versions of chromium don't support. Sadly the Chrome Store has stopped supporting V2 extensions, so I didn't really have a choice in that regard. The extension could be ported to V2 to work with older versions, but it would take some work, and it would require self-hosting as well. I just can't really justify doing it personally though.
