### ISSUE TITLE
Closes Immediately in Edge

### ISSUE THREAD

**Issue by r-neuschulz** [alyssaxuu/omni#45]
Thanks for the tool! Unfortunately i found omni unusable on my system. Whenever [Shift] + [Ctrl] + [K] is pressed on the Edge Browser, the action bar is not opening, but instead the "Get Started" Screen.

When the Extension is launched from the Extension Toolbar via mouseclick, however, it works as supposed.

**Comment by alyssaxuu** [comment]
Ahhh, that's because Ctrl+Shift+K on Edge (Windows specifically it appears) is already used for another function. You can change the shortcut by going here: edge://extensions/shortcuts

Unfortunately I don't think I will change the default command, it's very hard to find a command that's both easy to use and works in all OSs, browsers, websites, and in conjunction with other extensions at the same time. What I might do is release a separate Edge version that uses a different default command to fix the issue, and maybe add a disclaimer on the Chrome version that the command might cause issues and prompt the user to change it (since it can't be done automatically).
