### ISSUE TITLE
Did you steal my idea?

### ISSUE THREAD

**Issue by Explosion-Scratch** [alyssaxuu/omni#9]
I'm not sure if you stole my idea or not, it's possible you came up with this on your own, but it seems like you copied my extension which I made about a month ago.

https://github.com/Explosion-Scratch/tab_searcher

Screenshots of mine:
![image](https://user-images.githubusercontent.com/61319150/149221369-001f07ee-7aab-4397-9fc0-e8c0eed79092.png)
![image](https://user-images.githubusercontent.com/61319150/149221376-1c9b4e4b-8e69-4b00-a4cb-433f231223e8.png)
![image](https://user-images.githubusercontent.com/61319150/149221403-82576124-f0c6-4515-bbd1-8b7d93066450.png)
![image](https://user-images.githubusercontent.com/61319150/149221477-00b29e0c-fb5b-4341-b583-27fcd26d9902.png)

**Comment by alyssaxuu** [comment]
There's plenty of spotlight-like products out there: Raycast, Alfred, SlapDash...

Besides, I have been making concepts for it since October last year, as you can see [here](https://twitter.com/alyssaxuu/status/1449758848131153926) in a tweet.

In any case, it's honestly a bit odd to make such a claim (especially without even bothering to do any digging), you could have emailed me if anything, the email is even in the README.

**Comment by Explosion-Scratch** [comment]
> There's plenty of spotlight-like products out there: Raycast, Alfred, SlapDash...

True, I probably shouldn't have jumped to that conclusion

> Besides, I have been making concepts for it since October last year, as you can see [here](https://twitter.com/alyssaxuu/status/1449758848131153926) in a tweet.

Oh, ok.

> In any case, it's honestly a bit odd to make such a claim (especially without even bothering to do any digging), you could have emailed me if anything, the email is even in the README.

I feel like it was applicable to make an issue, I think it's best for things relating FOSS software to stay public.
